[FIX] arcsign-unseal.vobj:  Avoid keyword 'each'
The symptom was:

	# arcsign unseal $key $file
	.../arcsign.vx:86
	    ERROR: uncaught exception: "declarator operand must be a symbol"

The problem is that `def each {...}` was parsed as `def (each {...})` --
with `def` being given an iterator, not a symbol, for its operand (hence
the error).